// Blog manifest. To add a new blog:
//   1. Drop the blog folder into ./interactive_blogs/<slug>/index.html
//   2. Add one entry to the BLOGS array below (newest at the top).
//
// Fields:
//   slug       — folder name under interactive_blogs/
//   title      — card heading
//   category   — ONE broad bucket, used by the filter bar. Must be one of:
//                "Diffusion & Generative", "Attention & Sequence Models",
//                "Energy & Reasoning", "3D, Vision & World Models",
//                "Embodiment & Interaction", "Fundamentals & Theory".
//                (Keep this list in sync with CATEGORIES in index.html.)
//   tag        — free-form descriptive label shown top-right on the card (not filtered)
//   authors    — author shortlist
//   venue      — affiliation / conference
//   date       — paper or release date, freeform string
//   paper      — arXiv id / OpenReview / DOI, shown italic
//   blurb      — 2–4 sentences. HTML allowed (use <strong>, <em>).
//   highlights — small pill at the bottom (e.g. "5 widgets · 1 manim · ~3,400 words")

const BLOGS = [
  {
    slug: "slam",
    category: "3D, Vision & World Models",
    title: "SLAM: mapping a place and finding yourself at the same time",
    tag: "slam · odometry · loop closure · factor graph · triangulation · umi",
    authors: "A field guide",
    venue: "Explainer · visual & graph-based SLAM, with a look at UMI",
    date: "classic → 2026",
    paper: "EKF-SLAM · FastSLAM · iSAM/GTSAM · ORB-SLAM3 · UMI 2402.10329",
    blurb: `Drop a robot into a room with no map and no GPS and it faces a chicken-and-egg problem: it can't localize without a map, or map without knowing where it is. <strong>SLAM</strong> solves both at once — by writing every motion step, every sighting, and every "I've been here before" as a weighted constraint in one big sparse <em>factor graph</em>, then finding the trajectory and map that satisfy all of them. The star move is <strong>loop closure</strong>: recognizing a revisited place adds a constraint that snaps a drifted trajectory back into global consistency. We build it from odometry and drift up through least-squares smoothing — then show how the <strong>UMI</strong> data collector runs visual-inertial SLAM on a GoPro-on-a-gripper to turn in-the-wild human demos into robot actions.`,
    highlights: "5 widgets · 1 manim · ~3,300 words",
  },
  {
    slug: "gpu_crash_course",
    category: "Fundamentals & Theory",
    title: "Feed the Beast: a GPU crash course for AI researchers",
    tag: "gpu · cuda · triton · roofline · memory hierarchy · fusion",
    authors: "A field guide",
    venue: "Crash course & roadmap · for algorithm designers",
    date: "mental models → roadmap · 2026",
    paper: "Triton · PMPP · roofline · FlashAttention · CUTLASS",
    blurb: `You can train models for years without knowing what a GPU <em>is</em> — until you want to make something <em>faster</em> and hit a wall of jargon: warps, SMs, coalescing, occupancy, HBM. You don't need to become a hardware engineer. You need ~5 mental models and one master idea: <strong>the GPU's math is cheap; its bottleneck is moving data</strong>, so good algorithms move <em>less data</em>, not fewer FLOPs (that's the whole FlashAttention "magic"). The crash course — throughput vs latency, the memory hierarchy, the <strong>roofline</strong>, the four levers — plus a concrete <strong>roadmap</strong> of what to learn next, in what order, through what. The goal is momentum.`,
    highlights: "5 widgets · 1 manim · staged roadmap · ~3,100 words",
  },
  {
    slug: "speculative_decoding",
    category: "Fundamentals & Theory",
    title: "Speculative decoding: many tokens for the price of one",
    tag: "inference · draft model · rejection sampling · medusa · eagle · token trees",
    authors: "A field guide",
    venue: "Explainer · fast LLM inference",
    date: "2018 → 2026",
    paper: "Blockwise 1811.03115 · Speculative 2211.17192 · Spec. sampling 2302.01318 · Medusa 2401.10774 · EAGLE 2401.15077",
    blurb: `When a large model writes a paragraph, it spends most of its time <em>waiting for memory</em> — reading every weight to produce a single token while the GPU's math units sit idle. Speculative decoding turns that waste into speed: a small, cheap <strong>draft</strong> model guesses the next several tokens, and the big <strong>target</strong> model checks them all in <em>one</em> parallel pass. Most guesses are right, so you get a whole burst of tokens per expensive pass — a <strong>2–4× speedup</strong> — and a one-line identity, <em>min(p,q)+max(0,p−q)=p</em>, guarantees the output is <strong>provably identical</strong> to the big model's. This is the full tour: the memory wall, the accept/reject rule, the speedup math, and the family — Medusa, EAGLE, token trees, lookahead.`,
    highlights: "5 widgets · 1 manim · ~3,200 words",
  },
  {
    slug: "quantization",
    category: "Fundamentals & Theory",
    title: "Quantization: how neural networks shrink their numbers",
    tag: "fp32 · bf16 · fp8 · int8 · int4 · nf4 · gptq · awq · smoothquant",
    authors: "A field guide",
    venue: "Explainer · number formats & quantization techniques",
    date: "1985 → 2026",
    paper: "LLM.int8() 2208.07339 · GPTQ 2210.17323 · SmoothQuant 2211.10438 · QLoRA 2305.14314 · AWQ 2306.00978",
    blurb: `A 70-billion-parameter model stored as 32-bit floats needs <strong>280&nbsp;GB</strong> of memory — more than any single GPU. Quantization rewrites every weight in <em>fewer bits</em> — 16, 8, 4, sometimes barely one — while keeping the answers almost unchanged, so the <em>same</em> 70B model runs on one gaming GPU at <strong>35&nbsp;GB</strong>. This is the bit-by-bit tour: what <code>bf16</code>, <code>fp8</code>, <code>int8</code>, and <code>NF4</code> actually <em>are</em>, how to convert between them with a scale and a zero-point, the outlier problem, and the menagerie of techniques — <strong>GPTQ, AWQ, SmoothQuant, LLM.int8(), QLoRA</strong> — that all answer one question: given a tiny bit budget, where do you put the grid?`,
    highlights: "5 widgets · 1 manim · ~4,100 words",
  },
  {
    slug: "mixture_of_experts",
    category: "Attention & Sequence Models",
    title: "Mixture of Experts: from a 1991 committee to trillion-parameter LLMs",
    tag: "moe · routing · sparse · switch · mixtral · deepseek",
    authors: "Jacobs, Shazeer, Fedus, Jiang, Dai, et al.",
    venue: "Explainer · classical mixtures → sparse LLM MoE",
    date: "1991 → 2024",
    paper: "Sparse MoE 1701.06538 · Switch 2101.03961 · Mixtral 2401.04088 · DeepSeek-MoE 2401.06066",
    blurb: `You don't ask one doctor everything — you go to a specialist. The largest language models now work the same way: a <em>router</em> sends each token to a few <strong>expert</strong> sub-networks and ignores the rest, so a model can hold <em>trillions</em> of parameters while spending the compute of a small one. This is the full thread from the 1991 mixture of experts through <strong>Shazeer's</strong> sparsely-gated layer, the <strong>Switch</strong> Transformer's top-1 routing, and the load-balancing tricks, to <strong>Mixtral</strong> and <strong>DeepSeek</strong>. The one idea that unwelded <em>how big a model is</em> from <em>how much it costs to run</em>.`,
    highlights: "5 widgets · 1 manim · ~3,400 words",
  },
  {
    slug: "state_space_models",
    category: "Attention & Sequence Models",
    title: "State Space Models: from a swinging pendulum to Mamba",
    tag: "ssm · dynamical systems · hippo · s4 · mamba · selective scan",
    authors: "Gu, Dao, Ré, et al.",
    venue: "Explainer · classical control → modern SSMs",
    date: "2020 → 2024",
    paper: "HiPPO 2008.07669 · S4 2111.00396 · Mamba 2312.00752",
    blurb: `One little equation — <em>x′ = Ax + Bu</em> — describes a swinging pendulum, an RLC circuit, and a plane's autopilot. It also powers <strong>Mamba</strong>, a language model that runs in <strong>linear time</strong> and keeps improving on contexts up to a <em>million tokens</em>. This is the full thread from classical dynamical-systems theory — the state, the matrix exponential, eigenvalues, discretization — through <strong>HiPPO</strong>'s principled memory and <strong>S4</strong>'s recurrence↔convolution duality, to Mamba's <em>selective</em> state. The same state, read three ways: physical condition → compressed memory → memory that chooses.`,
    highlights: "5 widgets · 1 manim · ~4,000 words",
  },
  {
    slug: "attention_zoo",
    category: "Attention & Sequence Models",
    title: "The Attention Zoo: every escape from the quadratic curse",
    tag: "attention · survey · efficiency",
    authors: "A field guide",
    venue: "Survey · sparse · linear · SSM · RWKV · hybrid",
    date: "2019 → 2025",
    paper: "survey of 25+ methods",
    blurb: `Standard attention is <strong>O(n²)</strong>. Six years of escapes, organized into <strong>six families</strong>: sparse (skip cells), low-rank/linear (Linformer, Performer), state-space &amp; linear-RNN (<strong>Mamba, RWKV, RetNet</strong>), hardware/distributed (FlashAttention, Ring), and hybrids — plus the newest work from Chinese labs (DeepSeek NSA, Kimi MoBA, MiniMax lightning attention). A quick tutorial on each, then the honest question: <em>which actually ship in production, and which quietly didn't pan out?</em> Cross-links the <a href="sparse_attention/index.html">sparse attention</a> and <a href="flash_attention/index.html">FlashAttention</a> posts.`,
    highlights: "4 widgets · 1 manim · 25+ methods · ~2,800 words",
  },
  {
    slug: "sparse_attention",
    category: "Attention & Sequence Models",
    title: "Sparse attention: how to read a million tokens without reading them all",
    tag: "attention · long context · efficiency",
    authors: "Yuan et al. (DeepSeek) + the field",
    venue: "Topic explainer · anchored on NSA, ACL 2025",
    date: "February 2025",
    paper: "arXiv 2502.11089",
    blurb: `A Transformer compares every token to every other — that <strong>O(n²)</strong> wall is 70–80% of decoding latency at 64k context. Sparse attention skips most comparisons without losing what matters. Builds the theory from the cost equation up, walks the literature (Sparse Transformers → Longformer/BigBird → Reformer → block-sparse → <strong>Native Sparse Attention / MoBA</strong>), and lands on DeepSeek's NSA — three branches (compression + selection + sliding window), <strong>11.6× faster decode and 9× faster training at 64k</strong>, and it <em>beats</em> full attention on accuracy. Cross-links the <a href="flash_attention/index.html">FlashAttention</a> post.`,
    highlights: "4 widgets · 1 manim · 14-paper timeline · ~2,800 words",
  },
  {
    slug: "nerf",
    category: "3D, Vision & World Models",
    title: "NeRF: a scene is a function you can query",
    tag: "3D representation · neural fields",
    authors: "Mildenhall, Srinivasan, Tancik, Barron, Ramamoorthi, Ng",
    venue: "UC Berkeley / UCSD / Google · ECCV 2020",
    date: "March 2020",
    paper: "arXiv 2003.08934",
    blurb: `Store an entire 3D scene — geometry, color, the glint of a wet surface — inside the weights of one small neural network, with <em>no 3D data structure at all</em>. Feed it a point and a viewing direction; get back a color and a density. Render by firing a ray through each pixel and integrating. The result reset photorealistic view synthesis (<strong>40.15 dB PSNR vs 34.38 for the prior best</strong>) and defined the problem <a href="gaussian_splatting/index.html">3D Gaussian Splatting</a> later won on speed. Builds the method from the volume-rendering integral up: positional encoding & spectral bias, hierarchical sampling, and where neural fields sit among all 3D representations.`,
    highlights: "4 widgets · 1 manim · ~3,200 words",
  },
  {
    slug: "gaussian_splatting",
    category: "3D, Vision & World Models",
    title: "3D Gaussian Splatting: the primitive that ate 3D vision",
    tag: "3D representation · real-time radiance fields",
    authors: "Kerbl, Kopanas, Leimkühler, Drettakis",
    venue: "Inria / MPI · SIGGRAPH 2023",
    date: "August 2023",
    paper: "arXiv 2308.04079",
    blurb: `Represent a scene as a few million fuzzy, colored, semi-transparent ellipsoids — and optimize them directly with gradient descent, no neural network in the renderer, no ray marching. The result matched the best NeRF of the day while rendering <strong>~2,000× faster (134 fps vs 0.06)</strong> and training in 40 minutes instead of 48 hours. This explainer builds the theory from the anisotropic-Gaussian primitive up through the real-time rasterizer, maps the <strong>31-paper literature</strong> that exploded around it (a filterable timeline), surveys what splats are used for, and ends with an honest pros/cons of every other 3D representation — meshes, voxels, SDFs, point clouds, NeRFs.`,
    highlights: "5 widgets · 1 manim · 31-paper timeline · ~4,200 words",
  },
  {
    slug: "high_dim_geometry",
    category: "Fundamentals & Theory",
    title: "The strange geometry of high dimensions",
    tag: "fundamentals · geometry · concentration",
    authors: "An interactive tour",
    venue: "Fundamentals · ML intuition",
    date: "May 2026",
    paper: "9 phenomena, one theorem",
    blurb: `Almost everything you know about geometry comes from living in three dimensions. <em>None of it is true in a thousand.</em> A high-dim Gaussian is a thin shell, not a blob. A cube is mostly long spiky corners. Distances collapse onto a single number. Random vectors are nearly orthogonal. Nine of these phenomena, all derived from the same single principle — <strong>concentration of measure</strong> — each with a live widget and a paired ML callout: <strong>weight init, diffusion noise schedules, contrastive temperatures, LoRA, superposition, SAEs, FAISS</strong>, all the way down.`,
    highlights: "6 widgets · 1 manim · 10 ML callouts · ~5,500 words",
  },
  {
    slug: "elucidating_diffusion",
    category: "Diffusion & Generative",
    title: "Elucidating the Design Space of Diffusion-Based Generative Models",
    tag: "diffusion · sampling · design space",
    authors: "Karras, Aittala, Aila, Laine",
    venue: "NVIDIA · NeurIPS 2022",
    date: "June 2022",
    paper: "arXiv 2206.00364",
    blurb: `By 2022 the diffusion literature was three competing frameworks (VP, VE, iDDPM) each presenting an inseparable bundle of noise schedule, network output, and loss. EDM looks at the design space and asks: <em>what if these choices are actually independent?</em> The answer is yes — and decoupling them yields a sweet spot that handily beats every prior model. <strong>FID 1.79 on CIFAR-10 and 1.36 on ImageNet-64 using only 35 NFE per image</strong>, with a sampler swap that drops a pretrained model's FID from 2.07 to 1.55 without touching the weights.`,
    highlights: "4 widgets · 1 manim · ~3,300 words",
  },
  {
    slug: "ebt_policy",
    category: "Energy & Reasoning",
    title: "EBT-Policy: Energy Unlocks Emergent Physical Reasoning",
    tag: "robot policy · energy-based",
    authors: "Davies, Huang, Gladstone, Liu, Chen, Ji, Liu, Hu",
    venue: "ZhiCheng AI · UIUC · Tsinghua · Peking U",
    date: "October 2025",
    paper: "arXiv 2510.27545",
    blurb: `Diffusion Policy generates a robot's next moves by reversing a fixed ~100-step noise schedule — slow, and once it drifts out-of-distribution it cannot recover. EBT-Policy throws out the schedule: it learns a single <em>energy landscape</em> over action trajectories and generates by rolling downhill. The payoff is the same task in <strong>as few as 2 inference steps instead of 100</strong> (a 50× cut), in 55% fewer training epochs — and a behavior-cloned policy that <strong>retries after a failure it was never trained to recover from</strong>.`,
    highlights: "4 widgets · 1 manim · ~3,100 words",
  },
  {
    slug: "energy_based_transformers",
    category: "Energy & Reasoning",
    title: "Energy-Based Transformers are Scalable Learners and Thinkers",
    tag: "energy-based · System 2 thinking",
    authors: "Gladstone, Nanduru, Islam, Han, Ha, Chadha, Du, Ji, Li, Iqbal",
    venue: "UVA / UIUC / Amazon / Stanford / Harvard",
    date: "July 2025",
    paper: "arXiv 2507.02092",
    blurb: `Today's "reasoning models" only learn to think where an answer can be checked by a rule — math, code — because someone hand-built the checker. EBTs build the verifier <em>into the model</em>: instead of generating a prediction in one shot, they learn to <em>score</em> how well a candidate fits the context, then think by rolling that candidate downhill on the score until its energy converges. Entirely from unsupervised learning, in any modality, the payoff is <strong>up to 35% faster pretraining scaling, 29% more gain from extra inference compute where a vanilla Transformer gets nothing, and image denoising that beats a Diffusion Transformer with 99% fewer forward passes</strong>.`,
    highlights: "4 widgets · 1 manim · ~3,600 words",
  },
  {
    slug: "ired_energy_diffusion",
    category: "Energy & Reasoning",
    title: "Learning Iterative Reasoning through Energy Diffusion",
    tag: "reasoning · energy-based · test-time compute",
    authors: "Du, Mao, Tenenbaum",
    venue: "MIT CSAIL · ICML 2024",
    date: "June 2024",
    paper: "arXiv 2406.11179",
    blurb: `Stop predicting the answer — learn to <em>score</em> answers, then search. IRED casts reasoning as gradient descent on a learned energy function, annealed from a smooth landscape to a sharp one so the search never gets stuck. Because inference is explicit optimization, you can spend <em>more steps on harder problems</em> with the same frozen weights. On a Sudoku split with fewer clues than training, this lifts accuracy to <strong>62.1%</strong> — where a purpose-built SAT solver gets 3.2% and the previous best neural reasoner gets 28.6%.`,
    highlights: "4 widgets · 1 manim · ~3,200 words",
  },
  {
    slug: "ebft",
    category: "Energy & Reasoning",
    title: "Matching Features, Not Tokens: Energy-Based Fine-Tuning",
    tag: "LLM fine-tuning · energy-based",
    authors: "Jelassi, Kwun, Zhao, Li, Fusi, Du, Kakade, Domingo-Enrich",
    venue: "Harvard / Kempner · MBZUAI · Microsoft Research",
    date: "March 2026",
    paper: "arXiv 2603.12248",
    blurb: `Cross-entropy trains a model on <em>perfect</em> prefixes, then deploys it on its own imperfect output — a mismatch that lets a low-perplexity model drift over long generations. RL fixes it but needs a verifier and quietly wrecks the language model. EBFT matches <em>features</em>, not tokens: embed the model's rollouts and the ground-truth completion through a frozen network and align their statistics — a dense, verifier-free, sequence-level signal. It beats SFT, ties verifier-based RL, and <strong>reaches a validation cross-entropy of 0.207 vs 0.289 for the method built to minimize it</strong>.`,
    highlights: "4 widgets · 1 manim · ~3,700 words",
  },
  {
    slug: "ttt_discover",
    category: "Energy & Reasoning",
    title: "Learning to Discover at Test Time",
    tag: "test-time RL · scientific discovery",
    authors: "Yuksekgonul, Koceja, Li, Bianchi et al.",
    venue: "Stanford / NVIDIA / UC San Diego / Together AI",
    date: "January 2026",
    paper: "arXiv 2601.16175",
    blurb: `AlphaEvolve does AI-for-science by prompting a <em>frozen</em> model thousands of times — the model itself never learns. TTT-Discover turns test-time search into test-time <em>learning</em>: an open 120B model that trains on the single problem it is trying to solve, with an entropic objective that chases records and a PUCT rule for what to build on. <strong>It beats AlphaEvolve on the Erdős minimum overlap problem, makes a GPU kernel 2× faster than the best human expert, and would have won past AtCoder contests</strong> — for about $500 a problem.`,
    highlights: "4 widgets · 1 manim · ~3,900 words",
  },
  {
    slug: "normalization",
    category: "Fundamentals & Theory",
    title: "Every Normalization Layer Is the Same Layer",
    tag: "fundamentals · normalization",
    authors: "12 papers, one idea",
    venue: "Fundamentals",
    date: "2015 – 2025",
    paper: "BatchNorm → DynamicTanh",
    blurb: `BatchNorm, LayerNorm, GroupNorm, RMSNorm, adaLN — normalization is usually taught as a zoo of unrelated recipes. It isn't one. Every method is the <em>same layer</em> with a single knob turned differently: <strong>which axes do you average over?</strong> A from-scratch tour — the one recipe behind all of them, each method paired with the weakness it was built to answer, conditional norms (FiLM, AdaIN, adaLN-Zero), pre- vs post-norm placement, and the normalization-free frontier — ending in the cheat-sheet and the footguns that quietly cost you a weekend.`,
    highlights: "5 widgets · 1 manim · ~5,000 words",
  },
  {
    slug: "ttt",
    category: "Attention & Sequence Models",
    title: "Learning to (Learn at Test Time)",
    tag: "long context · architectures",
    authors: "Sun, Li, Dalal, Xu, Vikram, Zhang, Dubois et al.",
    venue: "Stanford / UC San Diego / UC Berkeley / Meta AI",
    date: "July 2024",
    paper: "arXiv 2407.04620",
    blurb: `RNNs run in linear time, but their fixed-size hidden state stalls in long context — Mamba's perplexity flattens after 16k tokens. TTT's move: make the hidden state itself a neural network, and the update rule a step of <em>self-supervised gradient descent</em>, so reading a sequence becomes training a model. <strong>TTT-Linear keeps improving past 16k where Mamba plateaus</strong> — and it is the framework the Titans memory is built on.`,
    highlights: "4 widgets · 1 manim · ~3,900 words",
  },
  {
    slug: "flow_equivariant_world_models",
    category: "3D, Vision & World Models",
    title: "Flow Equivariant World Models: memory for partially observed worlds",
    tag: "world models · equivariance",
    authors: "Lillemark, Huang, Zhan, Du, Keller",
    venue: "Harvard / UCSD / CMU",
    date: "January 2026",
    paper: "arXiv 2601.01075",
    blurb: `Modern video world models relearn motion from scratch on every frame. FloWM builds the symmetry in: agent self-motion and external object motion are unified as one-parameter Lie-group <em>flows</em>, and the latent map is constructed to flow in unison with the world. The payoff: <strong>100× lower MSE</strong> than the strongest diffusion baseline at 150-step extrapolation, and length generalization 7× past the training horizon.`,
    highlights: "5 widgets · 1 manim · ~4,500 words",
  },
  {
    slug: "flash_attention",
    category: "Attention & Sequence Models",
    title: "FlashAttention: fast, exact attention by knowing your GPU",
    tag: "systems · attention kernels",
    authors: "Dao, Fu, Ermon, Rudra, Ré",
    venue: "Stanford / Buffalo (NeurIPS 2022)",
    date: "May 2022",
    paper: "arXiv 2205.14135",
    blurb: `Attention is the bottleneck of every modern Transformer, and the dominant cost isn't math — it's memory traffic. FlashAttention rewrites attention as one CUDA kernel that keeps the N×N matrix in fast on-chip SRAM and never touches HBM. Identical math, <strong>3× faster on GPT-2, 20× less memory, first Transformer ever to solve Path-X at 16K tokens.</strong> Includes the GPU prerequisites — memory hierarchy, arithmetic intensity, online softmax — built from the ground up.`,
    highlights: "5 widgets · 1 manim · ~5,400 words",
  },
  {
    slug: "dit",
    category: "Diffusion & Generative",
    title: "DiT: Scalable Diffusion Models with Transformers",
    tag: "diffusion · architectures",
    authors: "Peebles, Xie",
    venue: "UC Berkeley / NYU (Meta AI FAIR)",
    date: "December 2022",
    paper: "arXiv 2212.09748",
    blurb: `Every state-of-the-art diffusion model in 2022 used a convolutional U-Net. DiT asked: <em>does the U-Net even matter?</em> No. Replace it with a plain ViT on latent patches plus adaLN-Zero conditioning and get <strong>FID 2.27</strong> on ImageNet 256×256 at <strong>10× fewer Gflops</strong> than ADM — the foundation that Sora and Stable Diffusion 3 are built on.`,
    highlights: "4 widgets · 1 manim · ~3,900 words",
  },
  {
    slug: "diffusion_dont_memorize",
    category: "Diffusion & Generative",
    title: "Why Diffusion Models Don't Memorize",
    tag: "diffusion · generalization theory",
    authors: "Bonnaire, Urfin, Biroli, Mézard",
    venue: "ENS Paris &amp; Bocconi",
    date: "May 2025",
    paper: "arXiv 2505.17638",
    blurb: `Score matching has a global minimum that perfectly reproduces every training image — and yet trained diffusion models generalize. The reason: two distinct training timescales, and the gap between them <strong>widens linearly with dataset size</strong>. Early stop in the window and you get a generalizing model for free, no architectural trick required.`,
    highlights: "4 widgets · 1 manim · ~4,500 words",
  },
  {
    slug: "titans",
    category: "Attention & Sequence Models",
    title: "Titans: Learning to Memorize at Test Time",
    tag: "long context · architectures",
    authors: "Behrouz, Zhong, Mirrokni",
    venue: "Google Research",
    date: "December 2024",
    paper: "arXiv 2501.00663",
    blurb: `What if memory was itself a neural network — trained by gradient descent <em>at inference time</em>? Titans replace the KV cache and the fixed RNN state with a small MLP whose weights drift token by token under an associative-memory loss, with momentum and forgetting. Scales to <strong>2M+ tokens</strong>; a 760M Titan beats GPT-4 on BABILong long-context reasoning.`,
    highlights: "5 widgets · 1 manim · ~3,700 words",
  },
  {
    slug: "back_to_basics_jit",
    category: "Diffusion & Generative",
    title: "Back to Basics: Let Denoising Generative Models Denoise",
    tag: "diffusion · pixel generation",
    authors: "Li, He",
    venue: "MIT",
    date: "November 2025",
    paper: "arXiv 2511.13720",
    blurb: `Modern diffusion models predict noise, not clean images — and Li &amp; He show that's a critical mistake at high resolution. Just predict the clean image with a plain ViT on raw pixel patches; ε-prediction loses by <strong>FID 8.6 vs 372</strong>. No tokenizer, no perceptual loss, no DINO alignment. <strong>FID 1.78 on ImageNet 512×512</strong>.`,
    highlights: "5 widgets · 1 manim · ~4,100 words",
  },
  {
    slug: "asymflow",
    category: "Diffusion & Generative",
    title: "Asymmetric Flow Models",
    tag: "diffusion · pixel generation",
    authors: "Chen, Ackermann, Kim, Wetzstein, Guibas",
    venue: "Stanford",
    date: "May 2026",
    paper: "arXiv 2605.12964",
    blurb: `Why pixel-space diffusion chokes plain transformers, and the one-projector fix that resolves it. Project the noise term of the velocity target onto a low-rank subspace — keep the data term full-rank — recover the full velocity analytically. <strong>FID 1.57</strong> on ImageNet 256, plus a 9B pixel-space text-to-image model that beats its own latent teacher.`,
    highlights: "4 widgets · 1 manim · ~4,000 words",
  },
  {
    slug: "ic_light",
    category: "Diffusion & Generative",
    title: "IC-Light: Scaling Illumination Editing",
    tag: "diffusion · relighting",
    authors: "Zhang, Rao, Agrawala",
    venue: "Stanford / HKUST",
    date: "ICLR 2025 (Oral)",
    paper: "OpenReview u1cQYxRI1H",
    blurb: `Why training relighting diffusion models breaks at scale, and the four-line physics identity that fixes it. Light transport is linear, so force the model's outputs to add up — across 10M+ images, three backbones (SD 1.5 / SDXL / Flux), and <strong>2× better LPIPS</strong> than the prior best. Free monocular normal estimator included.`,
    highlights: "4 widgets · 1 manim · ~4,200 words",
  },
  {
    slug: "image_generators_vision_learners",
    category: "3D, Vision & World Models",
    title: "Image Generators are Generalist Vision Learners",
    tag: "vision · foundation models",
    authors: "Gabeur, Long, Peng et al.",
    venue: "Google DeepMind",
    date: "April 2026",
    paper: "arXiv 2604.20329",
    blurb: `Hidden inside an image generator: a depth estimator, a segmenter, and a surface-normal predictor. Vision Banana unlocks them by instruction-tuning Nano Banana Pro to emit task outputs as RGB images, beating SAM 3 and Depth Anything 3 with no specialist architecture.`,
    highlights: "5 widgets · 1 manim · ~3,500 words",
  },
  {
    slug: "elf_embedded_language_flows",
    category: "Diffusion & Generative",
    title: "ELF: Embedded Language Flows",
    tag: "language diffusion",
    authors: "Hu, Qiu, Lu, Zhao, Li, Kim, Andreas, He",
    venue: "MIT",
    date: "May 2026",
    paper: "arXiv 2605.10938",
    blurb: `Continuous diffusion for language, done right. Flow matching in T5 embedding space, discretization only at the final time step, classifier-free guidance for free, and <strong>10× less training data</strong> than leading discrete and continuous baselines.`,
    highlights: "5 widgets · 1 manim · ~3,400 words",
  },
  {
    slug: "drifting",
    category: "Diffusion & Generative",
    title: "Generative Modeling via Drifting",
    tag: "generative modeling",
    authors: "Deng, Li, Li, Du, He",
    venue: "MIT",
    date: "February 2026",
    paper: "arXiv 2602.04770",
    blurb: `A new generative-modeling paradigm that moves the iteration from inference to training. Anti-symmetric drifting fields, attract+repel kernels, a three-line equilibrium proof, and <strong>FID 1.54</strong> in a single forward pass on ImageNet 256×256.`,
    highlights: "4 widgets · 1 manim · ~3,300 words",
  },
];
