// Blog manifest. To add a new blog:
//   1. Drop the blog folder into ./interactive_blogs/<slug>/index.html
//   2. Add one entry to the BLOGS array below (newest at the top).
//
// Fields:
//   slug       — folder name under interactive_blogs/
//   title      — card heading
//   tag        — single short category, shown top-right and used by tag filter
//   authors    — author shortlist
//   venue      — affiliation / conference
//   date       — paper or release date, freeform string
//   paper      — arXiv id / OpenReview / DOI, shown italic
//   blurb      — 2–4 sentences. HTML allowed (use <strong>, <em>).
//   highlights — small pill at the bottom (e.g. "5 widgets · 1 manim · ~3,400 words")

const BLOGS = [
  {
    slug: "ebt_policy",
    title: "EBT-Policy: Energy Unlocks Emergent Physical Reasoning",
    tag: "robot policy · energy-based",
    authors: "Davies, Huang, Gladstone, Liu, Chen, Ji, Liu, Hu",
    venue: "ZhiCheng AI · UIUC · Tsinghua · Peking U",
    date: "October 2025",
    paper: "arXiv 2510.27545",
    blurb: `Diffusion Policy generates a robot's next moves by reversing a fixed ~100-step noise schedule — slow, and once it drifts out-of-distribution it cannot recover. EBT-Policy throws out the schedule: it learns a single <em>energy landscape</em> over action trajectories and generates by rolling downhill. The payoff is the same task in <strong>as few as 2 inference steps instead of 100</strong> (a 50× cut), in 55% fewer training epochs — and a behavior-cloned policy that <strong>retries after a failure it was never trained to recover from</strong>.`,
    highlights: "4 widgets · 1 manim · ~3,100 words",
  },
  {
    slug: "energy_based_transformers",
    title: "Energy-Based Transformers are Scalable Learners and Thinkers",
    tag: "energy-based · System 2 thinking",
    authors: "Gladstone, Nanduru, Islam, Han, Ha, Chadha, Du, Ji, Li, Iqbal",
    venue: "UVA / UIUC / Amazon / Stanford / Harvard",
    date: "July 2025",
    paper: "arXiv 2507.02092",
    blurb: `Today's "reasoning models" only learn to think where an answer can be checked by a rule — math, code — because someone hand-built the checker. EBTs build the verifier <em>into the model</em>: instead of generating a prediction in one shot, they learn to <em>score</em> how well a candidate fits the context, then think by rolling that candidate downhill on the score until its energy converges. Entirely from unsupervised learning, in any modality, the payoff is <strong>up to 35% faster pretraining scaling, 29% more gain from extra inference compute where a vanilla Transformer gets nothing, and image denoising that beats a Diffusion Transformer with 99% fewer forward passes</strong>.`,
    highlights: "4 widgets · 1 manim · ~3,600 words",
  },
  {
    slug: "ired_energy_diffusion",
    title: "Learning Iterative Reasoning through Energy Diffusion",
    tag: "reasoning · energy-based · test-time compute",
    authors: "Du, Mao, Tenenbaum",
    venue: "MIT CSAIL · ICML 2024",
    date: "June 2024",
    paper: "arXiv 2406.11179",
    blurb: `Stop predicting the answer — learn to <em>score</em> answers, then search. IRED casts reasoning as gradient descent on a learned energy function, annealed from a smooth landscape to a sharp one so the search never gets stuck. Because inference is explicit optimization, you can spend <em>more steps on harder problems</em> with the same frozen weights. On a Sudoku split with fewer clues than training, this lifts accuracy to <strong>62.1%</strong> — where a purpose-built SAT solver gets 3.2% and the previous best neural reasoner gets 28.6%.`,
    highlights: "4 widgets · 1 manim · ~3,200 words",
  },
  {
    slug: "ebft",
    title: "Matching Features, Not Tokens: Energy-Based Fine-Tuning",
    tag: "LLM fine-tuning · energy-based",
    authors: "Jelassi, Kwun, Zhao, Li, Fusi, Du, Kakade, Domingo-Enrich",
    venue: "Harvard / Kempner · MBZUAI · Microsoft Research",
    date: "March 2026",
    paper: "arXiv 2603.12248",
    blurb: `Cross-entropy trains a model on <em>perfect</em> prefixes, then deploys it on its own imperfect output — a mismatch that lets a low-perplexity model drift over long generations. RL fixes it but needs a verifier and quietly wrecks the language model. EBFT matches <em>features</em>, not tokens: embed the model's rollouts and the ground-truth completion through a frozen network and align their statistics — a dense, verifier-free, sequence-level signal. It beats SFT, ties verifier-based RL, and <strong>reaches a validation cross-entropy of 0.207 vs 0.289 for the method built to minimize it</strong>.`,
    highlights: "4 widgets · 1 manim · ~3,700 words",
  },
  {
    slug: "ttt_discover",
    title: "Learning to Discover at Test Time",
    tag: "test-time RL · scientific discovery",
    authors: "Yuksekgonul, Koceja, Li, Bianchi et al.",
    venue: "Stanford / NVIDIA / UC San Diego / Together AI",
    date: "January 2026",
    paper: "arXiv 2601.16175",
    blurb: `AlphaEvolve does AI-for-science by prompting a <em>frozen</em> model thousands of times — the model itself never learns. TTT-Discover turns test-time search into test-time <em>learning</em>: an open 120B model that trains on the single problem it is trying to solve, with an entropic objective that chases records and a PUCT rule for what to build on. <strong>It beats AlphaEvolve on the Erdős minimum overlap problem, makes a GPU kernel 2× faster than the best human expert, and would have won past AtCoder contests</strong> — for about $500 a problem.`,
    highlights: "4 widgets · 1 manim · ~3,900 words",
  },
  {
    slug: "normalization",
    title: "Every Normalization Layer Is the Same Layer",
    tag: "fundamentals · normalization",
    authors: "12 papers, one idea",
    venue: "Fundamentals",
    date: "2015 – 2025",
    paper: "BatchNorm → DynamicTanh",
    blurb: `BatchNorm, LayerNorm, GroupNorm, RMSNorm, adaLN — normalization is usually taught as a zoo of unrelated recipes. It isn't one. Every method is the <em>same layer</em> with a single knob turned differently: <strong>which axes do you average over?</strong> A from-scratch tour — the one recipe behind all of them, each method paired with the weakness it was built to answer, conditional norms (FiLM, AdaIN, adaLN-Zero), pre- vs post-norm placement, and the normalization-free frontier — ending in the cheat-sheet and the footguns that quietly cost you a weekend.`,
    highlights: "5 widgets · 1 manim · ~5,000 words",
  },
  {
    slug: "ttt",
    title: "Learning to (Learn at Test Time)",
    tag: "long context · architectures",
    authors: "Sun, Li, Dalal, Xu, Vikram, Zhang, Dubois et al.",
    venue: "Stanford / UC San Diego / UC Berkeley / Meta AI",
    date: "July 2024",
    paper: "arXiv 2407.04620",
    blurb: `RNNs run in linear time, but their fixed-size hidden state stalls in long context — Mamba's perplexity flattens after 16k tokens. TTT's move: make the hidden state itself a neural network, and the update rule a step of <em>self-supervised gradient descent</em>, so reading a sequence becomes training a model. <strong>TTT-Linear keeps improving past 16k where Mamba plateaus</strong> — and it is the framework the Titans memory is built on.`,
    highlights: "4 widgets · 1 manim · ~3,900 words",
  },
  {
    slug: "flow_equivariant_world_models",
    title: "Flow Equivariant World Models: memory for partially observed worlds",
    tag: "world models · equivariance",
    authors: "Lillemark, Huang, Zhan, Du, Keller",
    venue: "Harvard / UCSD / CMU",
    date: "January 2026",
    paper: "arXiv 2601.01075",
    blurb: `Modern video world models relearn motion from scratch on every frame. FloWM builds the symmetry in: agent self-motion and external object motion are unified as one-parameter Lie-group <em>flows</em>, and the latent map is constructed to flow in unison with the world. The payoff: <strong>100× lower MSE</strong> than the strongest diffusion baseline at 150-step extrapolation, and length generalization 7× past the training horizon.`,
    highlights: "5 widgets · 1 manim · ~4,500 words",
  },
  {
    slug: "flash_attention",
    title: "FlashAttention: fast, exact attention by knowing your GPU",
    tag: "systems · attention kernels",
    authors: "Dao, Fu, Ermon, Rudra, Ré",
    venue: "Stanford / Buffalo (NeurIPS 2022)",
    date: "May 2022",
    paper: "arXiv 2205.14135",
    blurb: `Attention is the bottleneck of every modern Transformer, and the dominant cost isn't math — it's memory traffic. FlashAttention rewrites attention as one CUDA kernel that keeps the N×N matrix in fast on-chip SRAM and never touches HBM. Identical math, <strong>3× faster on GPT-2, 20× less memory, first Transformer ever to solve Path-X at 16K tokens.</strong> Includes the GPU prerequisites — memory hierarchy, arithmetic intensity, online softmax — built from the ground up.`,
    highlights: "5 widgets · 1 manim · ~5,400 words",
  },
  {
    slug: "dit",
    title: "DiT: Scalable Diffusion Models with Transformers",
    tag: "diffusion · architectures",
    authors: "Peebles, Xie",
    venue: "UC Berkeley / NYU (Meta AI FAIR)",
    date: "December 2022",
    paper: "arXiv 2212.09748",
    blurb: `Every state-of-the-art diffusion model in 2022 used a convolutional U-Net. DiT asked: <em>does the U-Net even matter?</em> No. Replace it with a plain ViT on latent patches plus adaLN-Zero conditioning and get <strong>FID 2.27</strong> on ImageNet 256×256 at <strong>10× fewer Gflops</strong> than ADM — the foundation that Sora and Stable Diffusion 3 are built on.`,
    highlights: "4 widgets · 1 manim · ~3,900 words",
  },
  {
    slug: "diffusion_dont_memorize",
    title: "Why Diffusion Models Don't Memorize",
    tag: "diffusion · generalization theory",
    authors: "Bonnaire, Urfin, Biroli, Mézard",
    venue: "ENS Paris &amp; Bocconi",
    date: "May 2025",
    paper: "arXiv 2505.17638",
    blurb: `Score matching has a global minimum that perfectly reproduces every training image — and yet trained diffusion models generalize. The reason: two distinct training timescales, and the gap between them <strong>widens linearly with dataset size</strong>. Early stop in the window and you get a generalizing model for free, no architectural trick required.`,
    highlights: "4 widgets · 1 manim · ~4,500 words",
  },
  {
    slug: "titans",
    title: "Titans: Learning to Memorize at Test Time",
    tag: "long context · architectures",
    authors: "Behrouz, Zhong, Mirrokni",
    venue: "Google Research",
    date: "December 2024",
    paper: "arXiv 2501.00663",
    blurb: `What if memory was itself a neural network — trained by gradient descent <em>at inference time</em>? Titans replace the KV cache and the fixed RNN state with a small MLP whose weights drift token by token under an associative-memory loss, with momentum and forgetting. Scales to <strong>2M+ tokens</strong>; a 760M Titan beats GPT-4 on BABILong long-context reasoning.`,
    highlights: "5 widgets · 1 manim · ~3,700 words",
  },
  {
    slug: "back_to_basics_jit",
    title: "Back to Basics: Let Denoising Generative Models Denoise",
    tag: "diffusion · pixel generation",
    authors: "Li, He",
    venue: "MIT",
    date: "November 2025",
    paper: "arXiv 2511.13720",
    blurb: `Modern diffusion models predict noise, not clean images — and Li &amp; He show that's a critical mistake at high resolution. Just predict the clean image with a plain ViT on raw pixel patches; ε-prediction loses by <strong>FID 8.6 vs 372</strong>. No tokenizer, no perceptual loss, no DINO alignment. <strong>FID 1.78 on ImageNet 512×512</strong>.`,
    highlights: "5 widgets · 1 manim · ~4,100 words",
  },
  {
    slug: "asymflow",
    title: "Asymmetric Flow Models",
    tag: "diffusion · pixel generation",
    authors: "Chen, Ackermann, Kim, Wetzstein, Guibas",
    venue: "Stanford",
    date: "May 2026",
    paper: "arXiv 2605.12964",
    blurb: `Why pixel-space diffusion chokes plain transformers, and the one-projector fix that resolves it. Project the noise term of the velocity target onto a low-rank subspace — keep the data term full-rank — recover the full velocity analytically. <strong>FID 1.57</strong> on ImageNet 256, plus a 9B pixel-space text-to-image model that beats its own latent teacher.`,
    highlights: "4 widgets · 1 manim · ~4,000 words",
  },
  {
    slug: "ic_light",
    title: "IC-Light: Scaling Illumination Editing",
    tag: "diffusion · relighting",
    authors: "Zhang, Rao, Agrawala",
    venue: "Stanford / HKUST",
    date: "ICLR 2025 (Oral)",
    paper: "OpenReview u1cQYxRI1H",
    blurb: `Why training relighting diffusion models breaks at scale, and the four-line physics identity that fixes it. Light transport is linear, so force the model's outputs to add up — across 10M+ images, three backbones (SD 1.5 / SDXL / Flux), and <strong>2× better LPIPS</strong> than the prior best. Free monocular normal estimator included.`,
    highlights: "4 widgets · 1 manim · ~4,200 words",
  },
  {
    slug: "image_generators_vision_learners",
    title: "Image Generators are Generalist Vision Learners",
    tag: "vision · foundation models",
    authors: "Gabeur, Long, Peng et al.",
    venue: "Google DeepMind",
    date: "April 2026",
    paper: "arXiv 2604.20329",
    blurb: `Hidden inside an image generator: a depth estimator, a segmenter, and a surface-normal predictor. Vision Banana unlocks them by instruction-tuning Nano Banana Pro to emit task outputs as RGB images, beating SAM 3 and Depth Anything 3 with no specialist architecture.`,
    highlights: "5 widgets · 1 manim · ~3,500 words",
  },
  {
    slug: "elf_embedded_language_flows",
    title: "ELF: Embedded Language Flows",
    tag: "language diffusion",
    authors: "Hu, Qiu, Lu, Zhao, Li, Kim, Andreas, He",
    venue: "MIT",
    date: "May 2026",
    paper: "arXiv 2605.10938",
    blurb: `Continuous diffusion for language, done right. Flow matching in T5 embedding space, discretization only at the final time step, classifier-free guidance for free, and <strong>10× less training data</strong> than leading discrete and continuous baselines.`,
    highlights: "5 widgets · 1 manim · ~3,400 words",
  },
  {
    slug: "drifting",
    title: "Generative Modeling via Drifting",
    tag: "generative modeling",
    authors: "Deng, Li, Li, Du, He",
    venue: "MIT",
    date: "February 2026",
    paper: "arXiv 2602.04770",
    blurb: `A new generative-modeling paradigm that moves the iteration from inference to training. Anti-symmetric drifting fields, attract+repel kernels, a three-line equilibrium proof, and <strong>FID 1.54</strong> in a single forward pass on ImageNet 256×256.`,
    highlights: "4 widgets · 1 manim · ~3,300 words",
  },
];
