// Blog manifest. To add a new blog:
//   1. Drop the blog folder into ./interactive_blogs/<slug>/index.html
//   2. Add one entry to the BLOGS array below (newest at the top).
//
// Fields:
//   slug       — folder name under interactive_blogs/
//   title      — card heading
//   category   — ONE broad bucket, used by the filter bar. Must be one of:
//                "Diffusion & Generative", "Sequence Architectures & Memory",
//                "Efficiency & Systems", "Energy & Reasoning",
//                "3D, Vision & World Models", "Embodiment & Interaction",
//                "Fundamentals & Theory".
//                (Keep this list in sync with CATEGORIES in index.html.)
//   tag        — free-form descriptive label shown top-right on the card (not filtered)
//   authors    — author shortlist
//   venue      — affiliation / conference
//   date       — paper or release date, freeform string
//   paper      — arXiv id / OpenReview / DOI, shown italic
//   blurb      — 2–4 sentences. HTML allowed (use <strong>, <em>).
//   highlights — small pill at the bottom (e.g. "5 widgets · 1 manim · ~3,400 words")

const BLOGS = [
  {
    slug: "differentiable_simulators",
    category: "Embodiment & Interaction",
    title: "Differentiable simulators: physics you can take the derivative of",
    tag: "differentiable physics · adjoint method · contact gradients · smoothing · robot co-design",
    authors: "Nimble, Dojo, Brax, MJX, Warp, Newton, DiffHand",
    venue: "a tour of the field, with one worked example",
    date: "August 2026",
    paper: "worked example: arXiv 2107.07501",
    blurb: `A normal simulator says what happens. A <em>differentiable</em> one says what would change if you turned any knob — every knob at once, for about <strong>twice the cost of one rollout</strong>, where finite differences would cost 2n. This post derives the adjoint method, shows the three ways engines actually compute gradients, and spends real time on the thing that breaks them all: contact is not smooth, so an exact gradient can be flat, exploding, or confidently pointing the wrong way. Then it surveys what exists today and ends with a paper that stretched the parameter vector as far as it goes — differentiating with respect to the robot's own geometry, so a gradient step grows a hook on a fingertip that then gets 3D printed.`,
    highlights: "6 widgets · 2 manim · ~7,000 words",
  },
  {
    slug: "agent_context_large_codebase",
    category: "Efficiency & Systems",
    title: "How coding agents handle a codebase that does not fit: context, search, and compaction",
    tag: "coding agents · context engineering · agentic search · compaction · AGENTS.md · context rot",
    authors: "Anthropic, OpenAI, Chroma, Liu, Salesforce AI, ETH Zurich, ByteDance Seed",
    venue: "engineering blogs + arXiv",
    date: "2023–2026",
    paper: "arXiv 2307.03172, 2511.13998, 2601.16746, 2602.11988",
    blurb: `A two-million-line repo is 40M tokens; a 200K window holds half a percent. So Claude Code and Codex never hold the codebase — they grep it, read a few files, and compact when full (Codex fires at a computed <strong>167K</strong> of 200K, then re-reads 5 files). Then the evidence gets strange: single-turn, the same tasks collapse <strong>29% → 3%</strong> as context grows to 1M, but agents with tools stay flat at <strong>0.71–0.75</strong> across a 100× codebase increase. And machine-written <code>AGENTS.md</code> files improved success rates by an amount indistinguishable from noise while adding <strong>20–23%</strong> to cost.`,
    highlights: "5 widgets · 1 manim · ~8,000 words",
  },
  {
    slug: "image_encoders",
    category: "3D, Vision & World Models",
    title: "Image encoders in vision-language models: SigLIP, its rivals, and how they take any image size",
    tag: "vision encoders · SigLIP · ViT · variable resolution · native aspect ratio · efficient inference",
    authors: "A field guide",
    venue: "built from the arXiv sources of SigLIP, SigLIP 2, NaViT, Pixtral, InternVL, Qwen2.5-VL and Perception Encoder",
    date: "July 2026",
    paper: "SigLIP 2303.15343 · SigLIP 2 2502.14786 · NaViT 2307.06304 · Pixtral 2410.07073 · Qwen2.5-VL 2502.13923",
    blurb: `A language model reads tokens; an image is not tokens. The encoder in between sets a
      hard ceiling on what the whole system can see. This takes it apart: the patch pipeline with
      real arithmetic, why SigLIP's per-pair sigmoid loss trains a strong model on
      <strong>four chips in one day</strong> where CLIP needed 256 for two weeks — and holds only a
      <em>b&times;b</em> block in memory instead of the full 32,768&times;32,768 matrix — what
      DINOv3, AIMv2 and Perception Encoder learn instead, the three different answers to "what if
      the image is not 224&times;224?" (tiling, packing at native resolution, and flexible sequence
      length), and what actually makes the encoder fast when you serve it.`,
    highlights: "5 widgets · 1 manim · ~9,700 words",
  },
  {
    slug: "audio_fundamentals",
    category: "Fundamentals & Theory",
    title: "Sound, from Air to Tokens: an audio crash course",
    tag: "crash course · sampling · STFT & mel · speech vs. music · the canon · evaluation",
    authors: "A field guide",
    venue: "Crash course & roadmap · for the ML person arriving in audio",
    date: "July 2026",
    paper: "Nyquist · STFT & mel · WaveNet · HiFi-GAN · HuBERT · EnCodec · VALL-E · MOS/FAD",
    blurb: `Audio looks like the easiest modality — one number, 44,100 times a second — and then your MSE loss converges to static. The reason is that <strong>a waveform is a terrible representation of what you actually perceive</strong>, and nearly every tool in the field is a workaround for that one fact. Builds the models in order: pressure waves and why everything is logarithmic, Nyquist and the 6 dB per bit rule, the STFT and the <strong>Δt · Δf = 1</strong> limit you cannot escape, why phase is the half nobody models, source–filter theory for speech, the canon from GMM-HMM to <strong>WaveNet → HiFi-GAN → HuBERT → EnCodec → VALL-E</strong>, and how to evaluate audio without fooling yourself. <strong>All five widgets make sound</strong> — including one that proves waveform MSE is meaningless.`,
    highlights: "5 audible widgets · 1 manim · ~6,700 words",
  },
  {
    slug: "guidance",
    category: "Diffusion & Generative",
    title: "Guidance in Diffusion and Flow Models",
    tag: "classifier guidance · classifier-free guidance · autoguidance · limited-interval guidance",
    authors: "A field guide",
    venue: "Explainer · classifier guidance, CFG, autoguidance, and limited-interval guidance",
    date: "2021 → 2024",
    paper: "Classifier guidance 2105.05233 · CFG 2207.12598 · Autoguidance 2406.02507 · Interval guidance 2404.07724",
    blurb: `Every "CFG scale" slider is the same three-term extrapolation: push <em>past</em> the model's honest conditional prediction, away from a "worse" reference, by weight w. What changes across four years of guidance research is only the answer to one question — what plays the worse role? An explicit noisy-image classifier, then the model's own unconditional self (the modern default, verified live in this page with the real toy-Gaussian-mixture math), then, in two independent 2024 papers published weeks apart, a <strong>smaller/undertrained copy of the same conditional model</strong> (autoguidance, new record FID <strong>1.25</strong> on ImageNet-512) or simply <strong>the right slice of the noise schedule</strong> (limited-interval guidance, FID <strong>1.40</strong>, plus a 20%+ inference speedup). Includes the real fidelity/diversity trade-off plotted from the original papers' own numbers, and the flow-matching analog used in Stable Diffusion 3-style models.`,
    highlights: "4 widgets · 1 manim · ~3,000 words",
  },
  {
    slug: "vq_vae",
    category: "Diffusion & Generative",
    title: "VQ-VAE: Neural Discrete Representation Learning",
    tag: "discrete latents · vector quantization · straight-through estimator · tokenizers",
    authors: "van den Oord, Vinyals, Kavukcuoglu",
    venue: "DeepMind · NeurIPS 2017",
    date: "November 2017",
    paper: "arXiv 1711.00937",
    blurb: `<code>argmin</code> has no useful gradient, so VQ-VAE just lies about it: copy the gradient computed at the quantized output <strong>straight back, unaltered</strong>, across a lookup table that has no real derivative at all. That one approximation — stabilized by a codebook loss, a commitment term, and a deterministic posterior that turns the KL term into a constant — is enough to train a genuinely discrete latent code end-to-end, dodge the "posterior collapse" that breaks continuous VAEs paired with strong decoders, compress a 128×128 ImageNet photo <strong>42.6×</strong>, and discover phoneme-level structure in raw speech with zero supervision (<strong>49.3%</strong> accuracy against a 7.2% chance baseline). The two-stage recipe it introduces — discretize first, model the tokens second — is the direct ancestor of VQGAN, DALL·E's image tokenizer, and most of what "tokenize, then generate" means today.`,
    highlights: "4 widgets · 1 manim · ~2,900 words",
  },
  {
    slug: "adajepa",
    category: "3D, Vision & World Models",
    title: "AdaJEPA: An Adaptive Latent World Model",
    tag: "jepa · world models · test-time adaptation · model predictive control · robotics",
    authors: "Wang, Bounou, LeCun, Ren",
    venue: "NYU / LeCun's group",
    date: "June 2026",
    paper: "arXiv 2606.32026",
    blurb: `Every JEPA world model — LeCun's 2022 proposal, LeWorldModel, SkyJEPA — shares one quiet assumption: once training ends, the model is frozen forever. AdaJEPA removes it with something almost too simple to be the whole story: after every action, take <strong>exactly one gradient step</strong> on the transition that just happened, threaded directly into the MPC replanning loop. On unseen object shapes, that one step very nearly <strong>doubles</strong> the success rate; in a low-data regime, a model adapted on 1,000 trajectories <strong>beats a frozen model trained on 16× more data</strong>. Four widgets (including a real plan-execute-adapt loop you click through) and one manim animation walk through why it works.`,
    highlights: "4 widgets · 1 manim · ~2,300 words",
  },
  {
    slug: "jepa_lineage",
    category: "3D, Vision & World Models",
    title: "The JEPA World-Model Lineage: From LeCun's 2022 Vision to LeWorldModel and SkyJEPA",
    tag: "jepa · world models · self-supervised learning · isotropic gaussian · sigreg · robotics",
    authors: "A field guide",
    venue: "Explainer · four connected papers, with a quiz at every node",
    date: "2022 → 2026",
    paper: "LeCun 2022 · LeJEPA 2511.08544 · LeWorldModel 2603.19312 · SkyJEPA 2606.23444",
    blurb: `Citation graphs get flattened into tidy chains — "X builds on Y builds on Z" — and this one doesn't hold up: checking what each paper's method section actually cites (not what the abstracts imply) reveals a <strong>branch, not a chain</strong>. LeCun's 2022 world-model proposal leaves an open question; <strong>LeJEPA</strong> (2025) answers it with a real theorem — embeddings should be an <strong>isotropic Gaussian</strong> to minimize worst-case risk on any downstream task — and a provably collapse-proof way (<strong>SIGReg</strong>) to train toward it. Two 2026 papers then independently import that exact result: <strong>LeWorldModel</strong> (pixel-based, cuts loss hyperparameters from six to one) and <strong>SkyJEPA</strong> (real-time quadrotor control, an 84% error reduction from one physics-inspired probe). Builds the whole toolkit from scratch — including a widget that runs the actual SIGReg gradient live in your browser — with a quiz at every node.`,
    highlights: "5 widgets · 1 manim · 5 quizzes · ~3,800 words",
  },
  {
    slug: "kv_cache",
    category: "Efficiency & Systems",
    title: "The KV Cache: Why LLM Inference Is a Memory Problem",
    tag: "kv cache · gqa · mla · pagedattention · vllm · attention sinks · h2o · prefix caching · quantization",
    authors: "A field guide",
    venue: "Explainer · from the attention equation to vLLM, GQA, MLA, and attention sinks",
    date: "2019 → 2026",
    paper: "MQA 1911.02150 · GQA 2305.13245 · vLLM 2309.06180 · StreamingLLM 2309.17453 · H2O 2306.14048 · DeepSeek-V2 2405.04434",
    blurb: `Every chat with an LLM quietly builds a tensor nobody talks about: on Llama-2-7B it grows <strong>half a megabyte per token</strong>, hits <strong>2&nbsp;GB per user</strong> by 4k context, and must be re-read in full for every generated token. That's the KV cache — the reason context length costs money and GPUs run out of memory before compute. Builds the object from the causal mask up, then the four fix axes: <strong>share</strong> it (GQA, now in every open model), <strong>compress</strong> it (DeepSeek's MLA: 93.3% smaller, <strong>5.76× throughput</strong>), <strong>page</strong> it (vLLM found prior systems keeping only 20–38% of cache memory useful), and <strong>prune</strong> it (evict 4 "attention sink" tokens and perplexity detonates from 5 to 5,000 — keep them and stream 4M tokens).`,
    highlights: "5 widgets · 1 manim · ~3,700 words",
  },
  {
    slug: "mpc",
    category: "Embodiment & Interaction",
    title: "Model Predictive Control: Planning by Replanning — from LQR to CEM and MPPI",
    tag: "optimal control · lqr · riccati · receding horizon · ilqr · cem · mppi · sampling-based planning",
    authors: "A field guide",
    venue: "Explainer · optimal control from the Riccati equation to GPU sampling",
    date: "1960 → 2026",
    paper: "MPPI 1707.02342 · PETS 1805.12114 · MJPC 2212.00541 · TD-MPC2 2310.16828",
    blurb: `A 22&nbsp;kg model car drifts at the edge of tire friction, steered by a GPU simulating <strong>1,200 possible futures every 25&nbsp;milliseconds</strong> — the same loop a chemical plant has run since 1979. MPC is not an optimization algorithm: it's a <em>replanning loop</em>, and the solver inside is swappable — exact (LQR via the Riccati recursion), gradient-based (iLQR), or sampling-based (<strong>CEM</strong>'s elite refitting and <strong>MPPI</strong>'s softmax-weighted rollouts), which took over robotics because contact, indicator costs, and learned models break gradients. Builds all four, then the modern synthesis: PETS matching model-free RL with <strong>8× fewer samples than SAC</strong>, and TD-MPC2 running MPPI inside a learned world model across 80 tasks.`,
    highlights: "5 widgets · 1 manim · ~4,600 words",
  },
  {
    slug: "optimizers",
    category: "Fundamentals & Theory",
    title: "Optimizers: Understanding Adam, Muon, and How to Judge a Training Algorithm",
    tag: "adam · adamw · muon · aurora · lion · shampoo · soap · muP · critical batch size · gradient noise scale",
    authors: "A field guide",
    venue: "Explainer · Adam from first principles, Muon's orthogonalized updates, and how to evaluate an optimizer",
    date: "1964 → 2026",
    paper: "Adam 1412.6980 · AdamW 1711.05101 · Muon (blog, 2024) · Kimi K2/MuonClip 2507.20534 · Aurora (Tilde, 2026) · Crowded Valley 2007.01547",
    blurb: `A five-line rescaling — divide by <strong>1&minus;&beta;&#8322;<sup>t</sup></strong> — is the exact fix for Adam's zero-initialization bias, and it's one of dozens of small, nameable fixes stacked into the optimizer every paper's method section reduces to one line. Builds Adam from its two 1960s&ndash;2012 ingredients (momentum, adaptive per-parameter scale) up, then <strong>Muon</strong> — which orthogonalizes the entire update matrix via a 5-step Newton-Schulz iteration instead of normalizing per-parameter, already cutting Moonshot AI's Kimi K2 (1&nbsp;trillion parameters) to <strong>zero loss spikes</strong> over 15.5T tokens — and <strong>Aurora</strong>, a days-old fix from Tilde Research for the "neuron death" Muon leaves behind on rectangular matrices. Plus what changes at scale (optimizer state alone can cost <strong>280&nbsp;GB</strong> for a 70B model), and why &gt;50,000 benchmark runs found "newer methods failing to significantly and consistently outperform" plain Adam.`,
    highlights: "5 widgets · 1 manim · ~4,400 words",
  },
  {
    slug: "data_quality",
    category: "Fundamentals & Theory",
    title: "Data Quality: How Do You Know Your Training Data Is Any Good?",
    tag: "data curation · deduplication · quality filtering · distribution matching · contamination · diversity metrics",
    authors: "A field guide",
    venue: "Explainer · the math and methods of judging training data, five case studies",
    date: "2019 → 2026",
    paper: "C4 · Gopher · CCNet · GPT-3 · Lee et al. dedup · SemDeDup · DSIR · FineWeb · RefinedWeb · LIMA",
    blurb: `A five-line logistic-regression classifier decided which sliver of the scraped web GPT-3 was allowed to read — no architecture change, just a filter. That's the real lesson of modern pretraining: <strong>"is this data good?" dissolves into five separate statistical tests</strong> — validity, redundancy, distributional fit, diversity, contamination — each with real math (MMD for distribution shift, the Vendi Score for diversity, a classifier two-sample test for distinguishability) and a real method (MinHash dedup, Gopher/C4 heuristics, DSIR importance resampling). Builds the full toolkit from scratch, then four case studies: GPT-3's 45TB→570GB filter, FineWeb-Edu beating the open web on <strong>10× fewer tokens</strong>, LIMA's 1,000 examples beating a 65B SFT set, and what happens when you skip deduplication (<strong>10× more memorization</strong>).`,
    highlights: "5 widgets · 1 manim · ~4,300 words",
  },
  {
    slug: "benchmarking_ml",
    category: "Fundamentals & Theory",
    title: "Benchmarking ML Models: How Do You Know It's Actually Good?",
    tag: "benchmarking · goodhart's law · evaluation · contamination · llm · image gen · robotics · video gen · math",
    authors: "A field guide",
    venue: "Explainer · principles, design, and five case studies",
    date: "2026",
    paper: "MMLU · GPQA · FID · GenEval · VBench · GSM8K · FrontierMath · miniF2F",
    blurb: `Every "new SOTA" claim rests on a number, and every number rests on a benchmark someone designed, with choices baked into its tape measure. GPT-3 scored 43.9% on MMLU against a 25% chance floor; five years later frontier models cleared 90% of a test whose human-expert ceiling is 89.8% — <strong>not obviously because models got better at everything, but because the test stopped being able to tell</strong>. We build the whole life cycle from scratch: what makes a benchmark trustworthy, Goodhart's Law in action with real saturation curves, how to design and maintain one against contamination — then spend most of the piece on <strong>five domains that each fought the same war differently</strong>: language models, image generation, robotics, video generation, and math.`,
    highlights: "4 widgets · 1 manim · 5 case studies · ~4,700 words",
  },
  {
    slug: "gated_deltanet",
    category: "Sequence Architectures & Memory",
    title: "Gated DeltaNet: Fixing Linear Attention with a Forget Gate and a Delta Rule",
    tag: "linear attention · delta rule · gating · gated attention · qwen3-next · kimi linear · hybrids",
    authors: "A field guide",
    venue: "Explainer · gated DeltaNet & the linear-attention frontier",
    date: "2024 → 2026",
    paper: "Gated DeltaNet 2412.06464 · DeltaNet 2406.06484 · Gated Attention 2505.06708 · Kimi Linear 2510.26692",
    blurb: `Softmax attention remembers <em>everything</em> — and pays with a cache that grows without bound. Linear attention promised a fixed-size memory you read and write in <em>O(1)</em>, but for years it simply <em>lost</em>. What brought it back are two old ideas: a <strong>forget gate</strong> (erase fast) and the <strong>delta rule</strong> (correct precisely). Bolt them together → the <strong>gated delta rule</strong>, the token mixer now inside <strong>Qwen3-Next</strong>, <strong>Qwen3.5</strong> and <strong>Kimi Linear</strong> — which reports <strong>6× faster decoding and a 75% smaller KV cache at 1M tokens</strong> while <em>beating</em> full attention. Build the one recurrence that contains them all, watch a memory overwrite and forget itself, meet the "gated attention" cousin that kills attention sinks, then dissect the real hybrids.`,
    highlights: "5 widgets · 1 manim · ~4,100 words",
  },
  {
    slug: "slam",
    category: "3D, Vision & World Models",
    title: "SLAM: mapping a place and finding yourself at the same time",
    tag: "slam · odometry · loop closure · factor graph · triangulation · umi",
    authors: "A field guide",
    venue: "Explainer · visual & graph-based SLAM, with a look at UMI",
    date: "classic → 2026",
    paper: "EKF-SLAM · FastSLAM · iSAM/GTSAM · ORB-SLAM3 · UMI 2402.10329",
    blurb: `Drop a robot into a room with no map and no GPS and it faces a chicken-and-egg problem: it can't localize without a map, or map without knowing where it is. <strong>SLAM</strong> solves both at once — by writing every motion step, every sighting, and every "I've been here before" as a weighted constraint in one big sparse <em>factor graph</em>, then finding the trajectory and map that satisfy all of them. The star move is <strong>loop closure</strong>: recognizing a revisited place adds a constraint that snaps a drifted trajectory back into global consistency. We build it from odometry and drift up through least-squares smoothing — then show how the <strong>UMI</strong> data collector runs visual-inertial SLAM on a GoPro-on-a-gripper to turn in-the-wild human demos into robot actions.`,
    highlights: "5 widgets · 1 manim · ~3,300 words",
  },
  {
    slug: "gpu_crash_course",
    category: "Efficiency & Systems",
    title: "Feed the Beast: a GPU crash course for AI researchers",
    tag: "gpu · cuda · triton · roofline · memory hierarchy · fusion",
    authors: "A field guide",
    venue: "Crash course & roadmap · for algorithm designers",
    date: "mental models → roadmap · 2026",
    paper: "Triton · PMPP · roofline · FlashAttention · CUTLASS",
    blurb: `You can train models for years without knowing what a GPU <em>is</em> — until you want to make something <em>faster</em> and hit a wall of jargon: warps, SMs, coalescing, occupancy, HBM. You don't need to become a hardware engineer. You need ~5 mental models and one master idea: <strong>the GPU's math is cheap; its bottleneck is moving data</strong>, so good algorithms move <em>less data</em>, not fewer FLOPs (that's the whole FlashAttention "magic"). The crash course — throughput vs latency, the memory hierarchy, the <strong>roofline</strong>, the four levers — plus a concrete <strong>roadmap</strong> of what to learn next, in what order, through what. The goal is momentum.`,
    highlights: "5 widgets · 1 manim · staged roadmap · ~3,100 words",
  },
  {
    slug: "speculative_decoding",
    category: "Efficiency & Systems",
    title: "Speculative decoding: many tokens for the price of one",
    tag: "inference · draft model · rejection sampling · medusa · eagle · token trees",
    authors: "A field guide",
    venue: "Explainer · fast LLM inference",
    date: "2018 → 2026",
    paper: "Blockwise 1811.03115 · Speculative 2211.17192 · Spec. sampling 2302.01318 · Medusa 2401.10774 · EAGLE 2401.15077",
    blurb: `When a large model writes a paragraph, it spends most of its time <em>waiting for memory</em> — reading every weight to produce a single token while the GPU's math units sit idle. Speculative decoding turns that waste into speed: a small, cheap <strong>draft</strong> model guesses the next several tokens, and the big <strong>target</strong> model checks them all in <em>one</em> parallel pass. Most guesses are right, so you get a whole burst of tokens per expensive pass — a <strong>2–4× speedup</strong> — and a one-line identity, <em>min(p,q)+max(0,p−q)=p</em>, guarantees the output is <strong>provably identical</strong> to the big model's. This is the full tour: the memory wall, the accept/reject rule, the speedup math, and the family — Medusa, EAGLE, token trees, lookahead.`,
    highlights: "5 widgets · 1 manim · ~3,200 words",
  },
  {
    slug: "quantization",
    category: "Efficiency & Systems",
    title: "Quantization: how neural networks shrink their numbers",
    tag: "fp32 · bf16 · fp8 · int8 · int4 · nf4 · gptq · awq · smoothquant",
    authors: "A field guide",
    venue: "Explainer · number formats & quantization techniques",
    date: "1985 → 2026",
    paper: "LLM.int8() 2208.07339 · GPTQ 2210.17323 · SmoothQuant 2211.10438 · QLoRA 2305.14314 · AWQ 2306.00978",
    blurb: `A 70-billion-parameter model stored as 32-bit floats needs <strong>280&nbsp;GB</strong> of memory — more than any single GPU. Quantization rewrites every weight in <em>fewer bits</em> — 16, 8, 4, sometimes barely one — while keeping the answers almost unchanged, so the <em>same</em> 70B model runs on one gaming GPU at <strong>35&nbsp;GB</strong>. This is the bit-by-bit tour: what <code>bf16</code>, <code>fp8</code>, <code>int8</code>, and <code>NF4</code> actually <em>are</em>, how to convert between them with a scale and a zero-point, the outlier problem, and the menagerie of techniques — <strong>GPTQ, AWQ, SmoothQuant, LLM.int8(), QLoRA</strong> — that all answer one question: given a tiny bit budget, where do you put the grid?`,
    highlights: "5 widgets · 1 manim · ~4,100 words",
  },
  {
    slug: "mixture_of_experts",
    category: "Efficiency & Systems",
    title: "Mixture of Experts: from a 1991 committee to trillion-parameter LLMs",
    tag: "moe · routing · sparse · switch · mixtral · deepseek",
    authors: "Jacobs, Shazeer, Fedus, Jiang, Dai, et al.",
    venue: "Explainer · classical mixtures → sparse LLM MoE",
    date: "1991 → 2024",
    paper: "Sparse MoE 1701.06538 · Switch 2101.03961 · Mixtral 2401.04088 · DeepSeek-MoE 2401.06066",
    blurb: `You don't ask one doctor everything — you go to a specialist. The largest language models now work the same way: a <em>router</em> sends each token to a few <strong>expert</strong> sub-networks and ignores the rest, so a model can hold <em>trillions</em> of parameters while spending the compute of a small one. This is the full thread from the 1991 mixture of experts through <strong>Shazeer's</strong> sparsely-gated layer, the <strong>Switch</strong> Transformer's top-1 routing, and the load-balancing tricks, to <strong>Mixtral</strong> and <strong>DeepSeek</strong>. The one idea that unwelded <em>how big a model is</em> from <em>how much it costs to run</em>.`,
    highlights: "5 widgets · 1 manim · ~3,400 words",
  },
  {
    slug: "state_space_models",
    category: "Sequence Architectures & Memory",
    title: "State Space Models: from a swinging pendulum to Mamba",
    tag: "ssm · dynamical systems · hippo · s4 · mamba · selective scan",
    authors: "Gu, Dao, Ré, et al.",
    venue: "Explainer · classical control → modern SSMs",
    date: "2020 → 2024",
    paper: "HiPPO 2008.07669 · S4 2111.00396 · Mamba 2312.00752",
    blurb: `One little equation — <em>x′ = Ax + Bu</em> — describes a swinging pendulum, an RLC circuit, and a plane's autopilot. It also powers <strong>Mamba</strong>, a language model that runs in <strong>linear time</strong> and keeps improving on contexts up to a <em>million tokens</em>. This is the full thread from classical dynamical-systems theory — the state, the matrix exponential, eigenvalues, discretization — through <strong>HiPPO</strong>'s principled memory and <strong>S4</strong>'s recurrence↔convolution duality, to Mamba's <em>selective</em> state. The same state, read three ways: physical condition → compressed memory → memory that chooses.`,
    highlights: "5 widgets · 1 manim · ~4,000 words",
  },
  {
    slug: "attention_zoo",
    category: "Efficiency & Systems",
    title: "The Attention Zoo: every escape from the quadratic curse",
    tag: "attention · survey · efficiency",
    authors: "A field guide",
    venue: "Survey · sparse · linear · SSM · RWKV · hybrid",
    date: "2019 → 2025",
    paper: "survey of 25+ methods",
    blurb: `Standard attention is <strong>O(n²)</strong>. Six years of escapes, organized into <strong>six families</strong>: sparse (skip cells), low-rank/linear (Linformer, Performer), state-space &amp; linear-RNN (<strong>Mamba, RWKV, RetNet</strong>), hardware/distributed (FlashAttention, Ring), and hybrids — plus the newest work from Chinese labs (DeepSeek NSA, Kimi MoBA, MiniMax lightning attention). A quick tutorial on each, then the honest question: <em>which actually ship in production, and which quietly didn't pan out?</em> Cross-links the <a href="sparse_attention/index.html">sparse attention</a> and <a href="flash_attention/index.html">FlashAttention</a> posts.`,
    highlights: "4 widgets · 1 manim · 25+ methods · ~2,800 words",
  },
  {
    slug: "sparse_attention",
    category: "Efficiency & Systems",
    title: "Sparse attention: how to read a million tokens without reading them all",
    tag: "attention · long context · efficiency",
    authors: "Yuan et al. (DeepSeek) + the field",
    venue: "Topic explainer · anchored on NSA, ACL 2025",
    date: "February 2025",
    paper: "arXiv 2502.11089",
    blurb: `A Transformer compares every token to every other — that <strong>O(n²)</strong> wall is 70–80% of decoding latency at 64k context. Sparse attention skips most comparisons without losing what matters. Builds the theory from the cost equation up, walks the literature (Sparse Transformers → Longformer/BigBird → Reformer → block-sparse → <strong>Native Sparse Attention / MoBA</strong>), and lands on DeepSeek's NSA — three branches (compression + selection + sliding window), <strong>11.6× faster decode and 9× faster training at 64k</strong>, and it <em>beats</em> full attention on accuracy. Cross-links the <a href="flash_attention/index.html">FlashAttention</a> post.`,
    highlights: "4 widgets · 1 manim · 14-paper timeline · ~2,800 words",
  },
  {
    slug: "nerf",
    category: "3D, Vision & World Models",
    title: "NeRF: a scene is a function you can query",
    tag: "3D representation · neural fields",
    authors: "Mildenhall, Srinivasan, Tancik, Barron, Ramamoorthi, Ng",
    venue: "UC Berkeley / UCSD / Google · ECCV 2020",
    date: "March 2020",
    paper: "arXiv 2003.08934",
    blurb: `Store an entire 3D scene — geometry, color, the glint of a wet surface — inside the weights of one small neural network, with <em>no 3D data structure at all</em>. Feed it a point and a viewing direction; get back a color and a density. Render by firing a ray through each pixel and integrating. The result reset photorealistic view synthesis (<strong>40.15 dB PSNR vs 34.38 for the prior best</strong>) and defined the problem <a href="gaussian_splatting/index.html">3D Gaussian Splatting</a> later won on speed. Builds the method from the volume-rendering integral up: positional encoding & spectral bias, hierarchical sampling, and where neural fields sit among all 3D representations.`,
    highlights: "4 widgets · 1 manim · ~3,200 words",
  },
  {
    slug: "gaussian_splatting",
    category: "3D, Vision & World Models",
    title: "3D Gaussian Splatting: the primitive that ate 3D vision",
    tag: "3D representation · real-time radiance fields",
    authors: "Kerbl, Kopanas, Leimkühler, Drettakis",
    venue: "Inria / MPI · SIGGRAPH 2023",
    date: "August 2023",
    paper: "arXiv 2308.04079",
    blurb: `Represent a scene as a few million fuzzy, colored, semi-transparent ellipsoids — and optimize them directly with gradient descent, no neural network in the renderer, no ray marching. The result matched the best NeRF of the day while rendering <strong>~2,000× faster (134 fps vs 0.06)</strong> and training in 40 minutes instead of 48 hours. This explainer builds the theory from the anisotropic-Gaussian primitive up through the real-time rasterizer, maps the <strong>31-paper literature</strong> that exploded around it (a filterable timeline), surveys what splats are used for, and ends with an honest pros/cons of every other 3D representation — meshes, voxels, SDFs, point clouds, NeRFs.`,
    highlights: "5 widgets · 1 manim · 31-paper timeline · ~4,200 words",
  },
  {
    slug: "high_dim_geometry",
    category: "Fundamentals & Theory",
    title: "The strange geometry of high dimensions",
    tag: "fundamentals · geometry · concentration",
    authors: "An interactive tour",
    venue: "Fundamentals · ML intuition",
    date: "May 2026",
    paper: "9 phenomena, one theorem",
    blurb: `Almost everything you know about geometry comes from living in three dimensions. <em>None of it is true in a thousand.</em> A high-dim Gaussian is a thin shell, not a blob. A cube is mostly long spiky corners. Distances collapse onto a single number. Random vectors are nearly orthogonal. Nine of these phenomena, all derived from the same single principle — <strong>concentration of measure</strong> — each with a live widget and a paired ML callout: <strong>weight init, diffusion noise schedules, contrastive temperatures, LoRA, superposition, SAEs, FAISS</strong>, all the way down.`,
    highlights: "6 widgets · 1 manim · 10 ML callouts · ~5,500 words",
  },
  {
    slug: "elucidating_diffusion",
    category: "Diffusion & Generative",
    title: "Elucidating the Design Space of Diffusion-Based Generative Models",
    tag: "diffusion · sampling · design space",
    authors: "Karras, Aittala, Aila, Laine",
    venue: "NVIDIA · NeurIPS 2022",
    date: "June 2022",
    paper: "arXiv 2206.00364",
    blurb: `By 2022 the diffusion literature was three competing frameworks (VP, VE, iDDPM) each presenting an inseparable bundle of noise schedule, network output, and loss. EDM looks at the design space and asks: <em>what if these choices are actually independent?</em> The answer is yes — and decoupling them yields a sweet spot that handily beats every prior model. <strong>FID 1.79 on CIFAR-10 and 1.36 on ImageNet-64 using only 35 NFE per image</strong>, with a sampler swap that drops a pretrained model's FID from 2.07 to 1.55 without touching the weights.`,
    highlights: "4 widgets · 1 manim · ~3,300 words",
  },
  {
    slug: "ebt_policy",
    category: "Energy & Reasoning",
    title: "EBT-Policy: Energy Unlocks Emergent Physical Reasoning",
    tag: "robot policy · energy-based",
    authors: "Davies, Huang, Gladstone, Liu, Chen, Ji, Liu, Hu",
    venue: "ZhiCheng AI · UIUC · Tsinghua · Peking U",
    date: "October 2025",
    paper: "arXiv 2510.27545",
    blurb: `Diffusion Policy generates a robot's next moves by reversing a fixed ~100-step noise schedule — slow, and once it drifts out-of-distribution it cannot recover. EBT-Policy throws out the schedule: it learns a single <em>energy landscape</em> over action trajectories and generates by rolling downhill. The payoff is the same task in <strong>as few as 2 inference steps instead of 100</strong> (a 50× cut), in 55% fewer training epochs — and a behavior-cloned policy that <strong>retries after a failure it was never trained to recover from</strong>.`,
    highlights: "4 widgets · 1 manim · ~3,100 words",
  },
  {
    slug: "energy_based_transformers",
    category: "Energy & Reasoning",
    title: "Energy-Based Transformers are Scalable Learners and Thinkers",
    tag: "energy-based · System 2 thinking",
    authors: "Gladstone, Nanduru, Islam, Han, Ha, Chadha, Du, Ji, Li, Iqbal",
    venue: "UVA / UIUC / Amazon / Stanford / Harvard",
    date: "July 2025",
    paper: "arXiv 2507.02092",
    blurb: `Today's "reasoning models" only learn to think where an answer can be checked by a rule — math, code — because someone hand-built the checker. EBTs build the verifier <em>into the model</em>: instead of generating a prediction in one shot, they learn to <em>score</em> how well a candidate fits the context, then think by rolling that candidate downhill on the score until its energy converges. Entirely from unsupervised learning, in any modality, the payoff is <strong>up to 35% faster pretraining scaling, 29% more gain from extra inference compute where a vanilla Transformer gets nothing, and image denoising that beats a Diffusion Transformer with 99% fewer forward passes</strong>.`,
    highlights: "4 widgets · 1 manim · ~3,600 words",
  },
  {
    slug: "ired_energy_diffusion",
    category: "Energy & Reasoning",
    title: "Learning Iterative Reasoning through Energy Diffusion",
    tag: "reasoning · energy-based · test-time compute",
    authors: "Du, Mao, Tenenbaum",
    venue: "MIT CSAIL · ICML 2024",
    date: "June 2024",
    paper: "arXiv 2406.11179",
    blurb: `Stop predicting the answer — learn to <em>score</em> answers, then search. IRED casts reasoning as gradient descent on a learned energy function, annealed from a smooth landscape to a sharp one so the search never gets stuck. Because inference is explicit optimization, you can spend <em>more steps on harder problems</em> with the same frozen weights. On a Sudoku split with fewer clues than training, this lifts accuracy to <strong>62.1%</strong> — where a purpose-built SAT solver gets 3.2% and the previous best neural reasoner gets 28.6%.`,
    highlights: "4 widgets · 1 manim · ~3,200 words",
  },
  {
    slug: "ebft",
    category: "Energy & Reasoning",
    title: "Matching Features, Not Tokens: Energy-Based Fine-Tuning",
    tag: "LLM fine-tuning · energy-based",
    authors: "Jelassi, Kwun, Zhao, Li, Fusi, Du, Kakade, Domingo-Enrich",
    venue: "Harvard / Kempner · MBZUAI · Microsoft Research",
    date: "March 2026",
    paper: "arXiv 2603.12248",
    blurb: `Cross-entropy trains a model on <em>perfect</em> prefixes, then deploys it on its own imperfect output — a mismatch that lets a low-perplexity model drift over long generations. RL fixes it but needs a verifier and quietly wrecks the language model. EBFT matches <em>features</em>, not tokens: embed the model's rollouts and the ground-truth completion through a frozen network and align their statistics — a dense, verifier-free, sequence-level signal. It beats SFT, ties verifier-based RL, and <strong>reaches a validation cross-entropy of 0.207 vs 0.289 for the method built to minimize it</strong>.`,
    highlights: "4 widgets · 1 manim · ~3,700 words",
  },
  {
    slug: "ttt_discover",
    category: "Energy & Reasoning",
    title: "Learning to Discover at Test Time",
    tag: "test-time RL · scientific discovery",
    authors: "Yuksekgonul, Koceja, Li, Bianchi et al.",
    venue: "Stanford / NVIDIA / UC San Diego / Together AI",
    date: "January 2026",
    paper: "arXiv 2601.16175",
    blurb: `AlphaEvolve does AI-for-science by prompting a <em>frozen</em> model thousands of times — the model itself never learns. TTT-Discover turns test-time search into test-time <em>learning</em>: an open 120B model that trains on the single problem it is trying to solve, with an entropic objective that chases records and a PUCT rule for what to build on. <strong>It beats AlphaEvolve on the Erdős minimum overlap problem, makes a GPU kernel 2× faster than the best human expert, and would have won past AtCoder contests</strong> — for about $500 a problem.`,
    highlights: "4 widgets · 1 manim · ~3,900 words",
  },
  {
    slug: "normalization",
    category: "Fundamentals & Theory",
    title: "Every Normalization Layer Is the Same Layer",
    tag: "fundamentals · normalization",
    authors: "12 papers, one idea",
    venue: "Fundamentals",
    date: "2015 – 2025",
    paper: "BatchNorm → DynamicTanh",
    blurb: `BatchNorm, LayerNorm, GroupNorm, RMSNorm, adaLN — normalization is usually taught as a zoo of unrelated recipes. It isn't one. Every method is the <em>same layer</em> with a single knob turned differently: <strong>which axes do you average over?</strong> A from-scratch tour — the one recipe behind all of them, each method paired with the weakness it was built to answer, conditional norms (FiLM, AdaIN, adaLN-Zero), pre- vs post-norm placement, and the normalization-free frontier — ending in the cheat-sheet and the footguns that quietly cost you a weekend.`,
    highlights: "5 widgets · 1 manim · ~5,000 words",
  },
  {
    slug: "ttt",
    category: "Sequence Architectures & Memory",
    title: "Learning to (Learn at Test Time)",
    tag: "long context · architectures",
    authors: "Sun, Li, Dalal, Xu, Vikram, Zhang, Dubois et al.",
    venue: "Stanford / UC San Diego / UC Berkeley / Meta AI",
    date: "July 2024",
    paper: "arXiv 2407.04620",
    blurb: `RNNs run in linear time, but their fixed-size hidden state stalls in long context — Mamba's perplexity flattens after 16k tokens. TTT's move: make the hidden state itself a neural network, and the update rule a step of <em>self-supervised gradient descent</em>, so reading a sequence becomes training a model. <strong>TTT-Linear keeps improving past 16k where Mamba plateaus</strong> — and it is the framework the Titans memory is built on.`,
    highlights: "4 widgets · 1 manim · ~3,900 words",
  },
  {
    slug: "flow_equivariant_world_models",
    category: "3D, Vision & World Models",
    title: "Flow Equivariant World Models: memory for partially observed worlds",
    tag: "world models · equivariance",
    authors: "Lillemark, Huang, Zhan, Du, Keller",
    venue: "Harvard / UCSD / CMU",
    date: "January 2026",
    paper: "arXiv 2601.01075",
    blurb: `Modern video world models relearn motion from scratch on every frame. FloWM builds the symmetry in: agent self-motion and external object motion are unified as one-parameter Lie-group <em>flows</em>, and the latent map is constructed to flow in unison with the world. The payoff: <strong>100× lower MSE</strong> than the strongest diffusion baseline at 150-step extrapolation, and length generalization 7× past the training horizon.`,
    highlights: "5 widgets · 1 manim · ~4,500 words",
  },
  {
    slug: "flash_attention",
    category: "Efficiency & Systems",
    title: "FlashAttention: fast, exact attention by knowing your GPU",
    tag: "systems · attention kernels",
    authors: "Dao, Fu, Ermon, Rudra, Ré",
    venue: "Stanford / Buffalo (NeurIPS 2022)",
    date: "May 2022",
    paper: "arXiv 2205.14135",
    blurb: `Attention is the bottleneck of every modern Transformer, and the dominant cost isn't math — it's memory traffic. FlashAttention rewrites attention as one CUDA kernel that keeps the N×N matrix in fast on-chip SRAM and never touches HBM. Identical math, <strong>3× faster on GPT-2, 20× less memory, first Transformer ever to solve Path-X at 16K tokens.</strong> Includes the GPU prerequisites — memory hierarchy, arithmetic intensity, online softmax — built from the ground up.`,
    highlights: "5 widgets · 1 manim · ~5,400 words",
  },
  {
    slug: "dit",
    category: "Diffusion & Generative",
    title: "DiT: Scalable Diffusion Models with Transformers",
    tag: "diffusion · architectures",
    authors: "Peebles, Xie",
    venue: "UC Berkeley / NYU (Meta AI FAIR)",
    date: "December 2022",
    paper: "arXiv 2212.09748",
    blurb: `Every state-of-the-art diffusion model in 2022 used a convolutional U-Net. DiT asked: <em>does the U-Net even matter?</em> No. Replace it with a plain ViT on latent patches plus adaLN-Zero conditioning and get <strong>FID 2.27</strong> on ImageNet 256×256 at <strong>10× fewer Gflops</strong> than ADM — the foundation that Sora and Stable Diffusion 3 are built on.`,
    highlights: "4 widgets · 1 manim · ~3,900 words",
  },
  {
    slug: "diffusion_dont_memorize",
    category: "Diffusion & Generative",
    title: "Why Diffusion Models Don't Memorize",
    tag: "diffusion · generalization theory",
    authors: "Bonnaire, Urfin, Biroli, Mézard",
    venue: "ENS Paris &amp; Bocconi",
    date: "May 2025",
    paper: "arXiv 2505.17638",
    blurb: `Score matching has a global minimum that perfectly reproduces every training image — and yet trained diffusion models generalize. The reason: two distinct training timescales, and the gap between them <strong>widens linearly with dataset size</strong>. Early stop in the window and you get a generalizing model for free, no architectural trick required.`,
    highlights: "4 widgets · 1 manim · ~4,500 words",
  },
  {
    slug: "titans",
    category: "Sequence Architectures & Memory",
    title: "Titans: Learning to Memorize at Test Time",
    tag: "long context · architectures",
    authors: "Behrouz, Zhong, Mirrokni",
    venue: "Google Research",
    date: "December 2024",
    paper: "arXiv 2501.00663",
    blurb: `What if memory was itself a neural network — trained by gradient descent <em>at inference time</em>? Titans replace the KV cache and the fixed RNN state with a small MLP whose weights drift token by token under an associative-memory loss, with momentum and forgetting. Scales to <strong>2M+ tokens</strong>; a 760M Titan beats GPT-4 on BABILong long-context reasoning.`,
    highlights: "5 widgets · 1 manim · ~3,700 words",
  },
  {
    slug: "back_to_basics_jit",
    category: "Diffusion & Generative",
    title: "Back to Basics: Let Denoising Generative Models Denoise",
    tag: "diffusion · pixel generation",
    authors: "Li, He",
    venue: "MIT",
    date: "November 2025",
    paper: "arXiv 2511.13720",
    blurb: `Modern diffusion models predict noise, not clean images — and Li &amp; He show that's a critical mistake at high resolution. Just predict the clean image with a plain ViT on raw pixel patches; ε-prediction loses by <strong>FID 8.6 vs 372</strong>. No tokenizer, no perceptual loss, no DINO alignment. <strong>FID 1.78 on ImageNet 512×512</strong>.`,
    highlights: "5 widgets · 1 manim · ~4,100 words",
  },
  {
    slug: "asymflow",
    category: "Diffusion & Generative",
    title: "Asymmetric Flow Models",
    tag: "diffusion · pixel generation",
    authors: "Chen, Ackermann, Kim, Wetzstein, Guibas",
    venue: "Stanford",
    date: "May 2026",
    paper: "arXiv 2605.12964",
    blurb: `Why pixel-space diffusion chokes plain transformers, and the one-projector fix that resolves it. Project the noise term of the velocity target onto a low-rank subspace — keep the data term full-rank — recover the full velocity analytically. <strong>FID 1.57</strong> on ImageNet 256, plus a 9B pixel-space text-to-image model that beats its own latent teacher.`,
    highlights: "4 widgets · 1 manim · ~4,000 words",
  },
  {
    slug: "ic_light",
    category: "Diffusion & Generative",
    title: "IC-Light: Scaling Illumination Editing",
    tag: "diffusion · relighting",
    authors: "Zhang, Rao, Agrawala",
    venue: "Stanford / HKUST",
    date: "ICLR 2025 (Oral)",
    paper: "OpenReview u1cQYxRI1H",
    blurb: `Why training relighting diffusion models breaks at scale, and the four-line physics identity that fixes it. Light transport is linear, so force the model's outputs to add up — across 10M+ images, three backbones (SD 1.5 / SDXL / Flux), and <strong>2× better LPIPS</strong> than the prior best. Free monocular normal estimator included.`,
    highlights: "4 widgets · 1 manim · ~4,200 words",
  },
  {
    slug: "image_generators_vision_learners",
    category: "3D, Vision & World Models",
    title: "Image Generators are Generalist Vision Learners",
    tag: "vision · foundation models",
    authors: "Gabeur, Long, Peng et al.",
    venue: "Google DeepMind",
    date: "April 2026",
    paper: "arXiv 2604.20329",
    blurb: `Hidden inside an image generator: a depth estimator, a segmenter, and a surface-normal predictor. Vision Banana unlocks them by instruction-tuning Nano Banana Pro to emit task outputs as RGB images, beating SAM 3 and Depth Anything 3 with no specialist architecture.`,
    highlights: "5 widgets · 1 manim · ~3,500 words",
  },
  {
    slug: "elf_embedded_language_flows",
    category: "Diffusion & Generative",
    title: "ELF: Embedded Language Flows",
    tag: "language diffusion",
    authors: "Hu, Qiu, Lu, Zhao, Li, Kim, Andreas, He",
    venue: "MIT",
    date: "May 2026",
    paper: "arXiv 2605.10938",
    blurb: `Continuous diffusion for language, done right. Flow matching in T5 embedding space, discretization only at the final time step, classifier-free guidance for free, and <strong>10× less training data</strong> than leading discrete and continuous baselines.`,
    highlights: "5 widgets · 1 manim · ~3,400 words",
  },
  {
    slug: "drifting",
    category: "Diffusion & Generative",
    title: "Generative Modeling via Drifting",
    tag: "generative modeling",
    authors: "Deng, Li, Li, Du, He",
    venue: "MIT",
    date: "February 2026",
    paper: "arXiv 2602.04770",
    blurb: `A new generative-modeling paradigm that moves the iteration from inference to training. Anti-symmetric drifting fields, attract+repel kernels, a three-line equilibrium proof, and <strong>FID 1.54</strong> in a single forward pass on ImageNet 256×256.`,
    highlights: "4 widgets · 1 manim · ~3,300 words",
  },
];
